### PR TITLE
Upgrade cucumber to 2.0.0

### PR DESCRIPTION
**Pull request by nicerloop**
Upgraded cucumber to 2.0.0
Checked for compatibility with cucumber 2.0.0 to 3.0.2

### CODE REVIEW

**Comment by acooper106** [comment]
When will this be available? I would like to test this new version

**Comment by alexvictoor** [comment]
Hello all,
Thanks for this PR.  I need a few days to take care of this, if everything goes well a new version should be released by the end of the week.

**Comment by alexvictoor** [comment]
@nicerloop could you rename the commit message? I guess you made a typo ;) Thanks!

**Comment by nicerloop** [comment]
Corrected typo

**Comment by alexvictoor** [comment]
@nicerloop Thanks!
Looks good to me!

**Comment by acooper106** [comment]
Should this version also work with previous version of cucumber?

<dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-html</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>pro-plugin</artifactId>
            <version>2.1.1</version>
        </dependency>

Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

**Comment by nicerloop** [comment]
As stated in the compatibility matrix, compatibility is with cucumber versions 2.x and 3.x. There was a breaking change between cucumber 1.x and 2.x on the integration classes, and another one with cucumber 4.x version.

**Comment by acooper106** [comment]
So there is no way to make it backwards compatible with version 1.x.x ?
I’m facing a challenge on how to introduce either the new version of cucumber or the new version of mutation without breaking people.
Looks like your telling me the break is unavoidable, because cucumber 2.x.x is not backwards compatible. ☹

Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

**Comment by nicerloop** [comment]
I still don't get what you want to do. This plugin has version 0.5 compatible with cucumber 1.x, version 0.6 compatible with cucumber 2.x to 3.x, and proposed version 0.7 (see other pull request) compatible with cucumber 4.x. All I did was implement compatibility with new versions of cucumber, nothing else, so you should be able to choose the appropriate version of the plugin depending on the version of cucumber you use.

**Comment by acooper106** [comment]
I wish version 0.6 was also compatible with cucumber 1.x – 3.x so that when I update to 0.6 I don’t break the people using 1.x


Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

**Comment by acooper106** [comment]
Has anyone noticed any changes in the mutation coverage percentage after the change?
For one of the projects that I’m testing on the mutation coverage went from 100% to 58% the project only have cucumber tests.

Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

From: Cooper,Allegra Bianca
Sent: Wednesday, November 14, 2018 1:32 PM
To: 'alexvictoor/pitest-cucumber-plugin' <reply@reply.github.com>; alexvictoor/pitest-cucumber-plugin <pitest-cucumber-plugin@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [External] Re: [alexvictoor/pitest-cucumber-plugin] Upgrade cucumber to 2.0.0 (#18)

I wish version 0.6 was also compatible with cucumber 1.x – 3.x so that when I update to 0.6 I don’t break the people using 1.x


Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

**Pull request merged**
