### PR TITLE
Upgrade cucumber to 4.2.0 and pitest to 1.4.3

### PR DESCRIPTION
**Pull request by nicerloop**

### CODE REVIEW

**Comment by alexvictoor** [comment]
Thanks a lot for your PR, I get back to you asap

**Comment by acooper106** [comment]
looking forward to this change.

**Comment by alexvictoor** [comment]
A new release will come shortly
Thanks @nicerloop for the PR!

**Comment by acooper106** [comment]
Is anyone noticing the mutation coverage decreased with these new versions? Is this expected? Any doc on why the new versions would cause the  mutation coverage to decrease?

Thank You,
Allegra B. Cooper
IT Chief Technology Office - Testing Center of Excellence (TCoE<http://crewhub.vanguard.com/it/cop1/TestCoE/SitePages/Home.aspx>),
Enterprise Automation Engineer
Work (610) 669 - 9961

**Pull request merged**
