### PR TITLE
update to pitest 1.7.3 and cucumber 7.2.3

### PR DESCRIPTION
**Pull request by TwoClocks**
Update for support for pitest 1.7.x and cucumber 7.2.x

All the java tests don't work anymore. They assumed only the requested features will be found, but now all features are found and I don't know how to narrow the scope.

But it seems to work otherwise.

### CODE REVIEW

**Comment by alexvictoor** [comment]
Hello !
Sorry for the delay. I will try to do that shorty.

**Comment by alexvictoor** [comment]
@SJean-Marc Do you confirm this version works on your side? I need to check why the tests are broken. If you have any clue any help is appreciated.

**Comment by TwoClocks** [comment]
Two tests fail, and it looks like they received more tests than they expected. I expect something isn't be de-duped somplace. 
I have been running this version for a while. Seems to work ok.
Here is the output from the failing tests:

```
[ERROR] Failures: 
[ERROR]   ScenarioTestUnitTest.should_run_scenario_and_call_collector_when_ran:87 
eventBus.send(<any>);
Wanted 2 times:
-> at org.pitest.cucumber.ScenarioTestUnitTest.should_run_scenario_and_call_collector_when_ran(ScenarioTestUnitTest.java:87)
But was 5 times:
-> at io.cucumber.core.runner.TestCase.emitTestCaseMessage(TestCase.java:177)
-> at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:211)
-> at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:218)
-> at io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:224)
-> at io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:235)


[ERROR]   ScenarioTestUnitTest.should_run_scenario_and_call_collector_when_ran:87 
eventBus.send(<any>);
Wanted 2 times:
-> at org.pitest.cucumber.ScenarioTestUnitTest.should_run_scenario_and_call_collector_when_ran(ScenarioTestUnitTest.java:87)
But was 5 times:
-> at io.cucumber.core.runner.TestCase.emitTestCaseMessage(TestCase.java:177)
-> at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:211)
-> at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:218)
-> at io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:224)
-> at io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:235)

```

**Comment by SJean-Marc** [comment]
@alexvictoor for me it is working, however i didn't use it for long

**Comment by epradier** [comment]
@alexvictoor  @TwoClocks Hello ! do you have some news about the PR ? I'm very interested in this plugin, it would be indeed pretty good if we could ue it for newer version of cucumber.
Greetings

**Comment by odinnou** [comment]
Hi, can you give some feedback about the merge of this pull request?

**Comment by alexvictoor** [comment]
Hello!
Sorry again for the delay. I will try to merge this PR and release a new version by next week.

**Comment by odinnou** [comment]
Thank you!

**Comment by alexvictoor** [comment]
Hello!
I have just published a new version on https://oss.sonatype.org/

**Pull request merged**
