### PR TITLE
Update to support FIT 1.4.2 Release

### PR DESCRIPTION
**Pull request by FelixLee888**
Update to support FIT 1.4.3-SNAPSHOT, please help to review

### CODE REVIEW

**Comment by alexvictoor** [comment]
Thanks a lot for your PR!
I will take a look at it and get back to you as soon as I can
Cheers

**Comment by FelixLee888** [comment]
@alexvictoor Is there any feedback so far?

**Comment by alexvictoor** [comment]
Sorry for the delay, I have been quite busy.
I have trouble building the plugin because of the snapshot dependency. Have you changed your maven settings? Also why supporting a snapshot release of pitest instead of the latest release?
Regards

**Comment by FelixLee888** [comment]
@alexvictoor Thanks for your response, I am using snapshot because of the bugfix for mutation test matrics.  It is quite straight forward to switch back to 1.4.2 release without any code change.

**Comment by FelixLee888** [comment]
@alexvictoor Thanks for your response, I am using snapshot because of the bugfix for mutation test matrics.  It is quite straight forward to switch back to 1.4.2 release without any code change.

**Comment by FelixLee888** [comment]
@alexvictoor I could create another pull request with 1.4.2 release if you like, please share your thoughts.

**Comment by alexvictoor** [comment]
@FelixLee888 yes please update this PR or create a new one in order to target pit 1.4.2

**Comment by FelixLee888** [comment]
@alexvictoor I have been updated the pom.xml to support 1.4.2 release, please review.

**Comment by FelixLee888** [comment]
@alexvictoor may I know if you have feedback?

**Comment by alexvictoor** [comment]
Yes I get back to you in a few hours

**Pull request merged**
